# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 15:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=30)),
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_logo', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2016, 3, 28, 15, 34, 54, 447504, tzinfo=utc))),
                ('description', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('skills_reqd', models.CharField(max_length=100)),
                ('edu_background_reqd', models.CharField(max_length=100)),
                ('payment', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('date_of_birth', models.DateTimeField(default=datetime.datetime(2016, 3, 28, 15, 34, 54, 430666, tzinfo=utc))),
                ('password', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=100)),
                ('edu_background', models.CharField(max_length=100)),
                ('interests', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('profile_pic_loc', models.CharField(max_length=100)),
                ('participated_pid', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
